import { auth } from "@/auth";
import ChapterList from "@/components/chapter";
import ListSubjects from "@/components/listsubjects";
import Navbar from "@/components/navbar";
import NavbarAuth from "@/components/navbarAuthen";

const data = [
  {
    id: 1,
    nthChapter: "1",
    title: "A long and healthy life",
    lessonList: [
      {
        id: 1,
        nthLesson: "1",
        title: "Từ vựng",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 2,
        nthLesson: "2",
        title: "Luyện tập từ vựng",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 3,
        nthLesson: "3",
        title: "Ngữ pháp: Thì quá khứ đơn & hiện tại hoàn thành",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 4,
        nthLesson: "4",
        title: "I. Getting Started",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 5,
        nthLesson: "5",
        title: "II. Language",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 6,
        nthLesson: "6",
        title: "III. Reading",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 7,
        nthLesson: "7",
        title: "IV. Speaking",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 8,
        nthLesson: "8",
        title: "V. Listening",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 9,
        nthLesson: "9",
        title: "VI. Writing",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 10,
        nthLesson: "10",
        title: "VII. Communication and culture/ CLIL",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 11,
        nthLesson: "11",
        title: "VIII. Looking back",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 12,
        nthLesson: "12",
        title: "Project",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
    ],
  },
  {
    id: 2,
    nthChapter: "2",
    title: "The generation gap",
    lessonList: [
      {
        id: 1,
        nthLesson: "1",
        title: "Từ vựng",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 2,
        nthLesson: "2",
        title: "Luyện tập từ vựng",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 3,
        nthLesson: "3",
        title: "Ngữ pháp: Động từ khuyết thiếu must, have to, should",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 4,
        nthLesson: "4",
        title: "I. Getting Started",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 5,
        nthLesson: "5",
        title: "II. Language",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 6,
        nthLesson: "6",
        title: "III. Reading",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 7,
        nthLesson: "7",
        title: "IV. Speaking",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 8,
        nthLesson: "8",
        title: "V. Listening",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 9,
        nthLesson: "9",
        title: "VI. Writing",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 10,
        nthLesson: "10",
        title: "VII. Communication and culture/ CLIL",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 11,
        nthLesson: "11",
        title: "VIII. Looking back",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 12,
        nthLesson: "12",
        title: "Project",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
    ],
  },
  {
    id: 3,
    nthChapter: "3",
    title: "Cities of the future",
    lessonList: [
      {
        id: 1,
        nthLesson: "1",
        title: "Từ vựng",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 2,
        nthLesson: "2",
        title: "Luyện tập từ vựng",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 3,
        nthLesson: "3",
        title: "Ngữ pháp: Động từ trạng thái và động từ nối",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 4,
        nthLesson: "4",
        title: "I. Getting Started",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 5,
        nthLesson: "5",
        title: "II. Language",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 6,
        nthLesson: "6",
        title: "III. Reading",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 7,
        nthLesson: "7",
        title: "IV. Speaking",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 8,
        nthLesson: "8",
        title: "V. Listening",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 9,
        nthLesson: "9",
        title: "VI. Writing",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 10,
        nthLesson: "10",
        title: "VII. Communication and culture/ CLIL",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 11,
        nthLesson: "11",
        title: "VIII. Looking back",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 12,
        nthLesson: "12",
        title: "Project",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
    ],
  },
  {
    id: 4,
    nthChapter: "#",
    title: "Review 1",
    lessonList: [
      {
        id: 1,
        nthLesson: "1",
        title: "I. Language",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 2,
        nthLesson: "2",
        title: "II. Skills",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
    ],
  },
  {
    id: 5,
    nthChapter: "4",
    title: "ASEAN and Vietnam",
    lessonList: [
      {
        id: 1,
        nthLesson: "1",
        title: "Từ vựng",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 2,
        nthLesson: "2",
        title: "Luyện tập từ vựng",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 3,
        nthLesson: "3",
        title: "Ngữ pháp: Danh động từ có vai trò như chủ ngữ và tân ngữ",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 4,
        nthLesson: "4",
        title: "I. Getting Started",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 5,
        nthLesson: "5",
        title: "II. Language",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 6,
        nthLesson: "6",
        title: "III. Reading",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 7,
        nthLesson: "7",
        title: "IV. Speaking",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 8,
        nthLesson: "8",
        title: "V. Listening",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 9,
        nthLesson: "9",
        title: "VI. Writing",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 10,
        nthLesson: "10",
        title: "VII. Communication and culture/ CLIL",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 11,
        nthLesson: "11",
        title: "VIII. Looking back",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 12,
        nthLesson: "12",
        title: "Project",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
    ],
  },
  {
    id: 6,
    nthChapter: "5",
    title: "Global warming",
    lessonList: [
      {
        id: 1,
        nthLesson: "1",
        title: "Từ vựng",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 2,
        nthLesson: "2",
        title: "Luyện tập từ vựng",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 3,
        nthLesson: "3",
        title: "Ngữ pháp: Mệnh đề hiện tại phân từ và quá khứ phân từ",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 4,
        nthLesson: "4",
        title: "I. Getting Started",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 5,
        nthLesson: "5",
        title: "II. Language",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 6,
        nthLesson: "6",
        title: "III. Reading",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 7,
        nthLesson: "7",
        title: "IV. Speaking",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 8,
        nthLesson: "8",
        title: "V. Listening",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 9,
        nthLesson: "9",
        title: "VI. Writing",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 10,
        nthLesson: "10",
        title: "VII. Communication and culture/ CLIL",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 11,
        nthLesson: "11",
        title: "VIII. Looking back",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 12,
        nthLesson: "12",
        title: "Project",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
    ],
  },
  {
    id: 7,
    nthChapter: "#",
    title: "Review 2",
    lessonList: [
      {
        id: 1,
        nthLesson: "1",
        title: "I. Language",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 2,
        nthLesson: "2",
        title: "II. Skills",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
    ],
  },
  {
    id: 8,
    nthChapter: "6",
    title: "Preserving our heritage",
    lessonList: [
      {
        id: 1,
        nthLesson: "1",
        title: "Từ vựng",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 2,
        nthLesson: "2",
        title: "Luyện tập từ vựng",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 3,
        nthLesson: "3",
        title: "Ngữ pháp: Mệnh đề to-động từ nguyên thể",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 4,
        nthLesson: "4",
        title: "I. Getting Started",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 5,
        nthLesson: "5",
        title: "II. Language",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 6,
        nthLesson: "6",
        title: "III. Reading",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 7,
        nthLesson: "7",
        title: "IV. Speaking",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 8,
        nthLesson: "8",
        title: "V. Listening",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 9,
        nthLesson: "9",
        title: "VI. Writing",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 10,
        nthLesson: "10",
        title: "VII. Communication and culture/ CLIL",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 11,
        nthLesson: "11",
        title: "VIII. Looking back",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 12,
        nthLesson: "12",
        title: "Project",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
    ],
  },
  {
    id: 9,
    nthChapter: "7",
    title: "Education options for school-leavers",
    lessonList: [
      {
        id: 1,
        nthLesson: "1",
        title: "Từ vựng",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 2,
        nthLesson: "2",
        title: "Luyện tập từ vựng",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 3,
        nthLesson: "3",
        title: "Ngữ pháp: Danh động từ hoàn thành & Mệnh đề phân từ hoàn thành",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 4,
        nthLesson: "4",
        title: "I. Getting Started",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 5,
        nthLesson: "5",
        title: "II. Language",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 6,
        nthLesson: "6",
        title: "III. Reading",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 7,
        nthLesson: "7",
        title: "IV. Speaking",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 8,
        nthLesson: "8",
        title: "V. Listening",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 9,
        nthLesson: "9",
        title: "VI. Writing",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 10,
        nthLesson: "10",
        title: "VII. Communication and culture/ CLIL",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 11,
        nthLesson: "11",
        title: "VIII. Looking back",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 12,
        nthLesson: "12",
        title: "Project",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
    ],
  },
  {
    id: 10,
    nthChapter: "8",
    title: "Becoming independent",
    lessonList: [
      {
        id: 1,
        nthLesson: "1",
        title: "Từ vựng",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 2,
        nthLesson: "2",
        title: "Luyện tập từ vựng",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 3,
        nthLesson: "3",
        title: "Ngữ pháp: Câu chẻ với It is/ It was... that/who...",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 4,
        nthLesson: "4",
        title: "I. Getting Started",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 5,
        nthLesson: "5",
        title: "II. Language",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 6,
        nthLesson: "6",
        title: "III. Reading",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 7,
        nthLesson: "7",
        title: "IV. Speaking",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 8,
        nthLesson: "8",
        title: "V. Listening",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 9,
        nthLesson: "9",
        title: "VI. Writing",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 10,
        nthLesson: "10",
        title: "VII. Communication and culture/ CLIL",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 11,
        nthLesson: "11",
        title: "VIII. Looking back",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 12,
        nthLesson: "12",
        title: "Project",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
    ],
  },
  {
    id: 11,
    nthChapter: "#",
    title: "Review 3",
    lessonList: [
      {
        id: 1,
        nthLesson: "1",
        title: "I. Language",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 2,
        nthLesson: "2",
        title: "II. Skills",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
    ],
  },
  {
    id: 13,
    nthChapter: "10",
    title: "The ecosystem",
    lessonList: [
      {
        id: 1,
        nthLesson: "1",
        title: "Từ vựng",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 2,
        nthLesson: "2",
        title: "Luyện tập từ vựng",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 3,
        nthLesson: "3",
        title: "Ngữ pháp: Danh từ ghép",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 4,
        nthLesson: "4",
        title: "I. Getting Started",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 5,
        nthLesson: "5",
        title: "II. Language",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 6,
        nthLesson: "6",
        title: "III. Reading",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 7,
        nthLesson: "7",
        title: "IV. Speaking",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 8,
        nthLesson: "8",
        title: "V. Listening",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 9,
        nthLesson: "9",
        title: "VI. Writing",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 10,
        nthLesson: "10",
        title: "VII. Communication and culture/ CLIL",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 11,
        nthLesson: "11",
        title: "VIII. Looking back",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 12,
        nthLesson: "12",
        title: "Project",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
    ],
  },
  {
    id: 14,
    nthChapter: "#",
    title: "Review 4",
    lessonList: [
      {
        id: 1,
        nthLesson: "1",
        title: "I. Language",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
      {
        id: 2,
        nthLesson: "2",
        title: "II. Skills",
        context: "To do",
        isDone: false,
        linkTo: "#",
      },
    ],
  },
];

export default async function Page() {
  const session = await auth();
  const isLogin = !!session?.user;
  return (
    <>
      {isLogin && <NavbarAuth imageLink={session?.user?.image as string} />}
      {!isLogin && <Navbar />}
      <ListSubjects />

      <div className="container">
        {data.map((chapter) => {
          return (
            <div key={chapter.id} className="py-16">
              <ChapterList
                subject="anh"
                pref="UNIT"
                title={chapter.title}
                nthChapter={chapter.nthChapter}
                lessonList={chapter.lessonList}
              />
            </div>
          );
        })}
      </div>
    </>
  );
}
